### ISSUE TITLE
ModuleNotFoundError: No module named 'data.SDD.sdd'

### ISSUE THREAD

**Issue by RemGao** [Kguo-cs/TDOR#1]
Thank you for your  excellent work！

When I use this program,I have this bug. Could you give me some  advice?

(/home/thicv/anaconda3) thicv@thicv-DGX-Station:~$ cd  TDOR/
(/home/thicv/anaconda3) thicv@thicv-DGX-Station:~/TDOR$ python train.py  --dataset "trajnet"
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from data.SDD.sdd import sdd as DS
ModuleNotFoundError: No module named 'data.SDD.sdd'

**Comment by Kguo-cs** [comment]
You need to download it from the google drive I provided. Hope it helps.
