### ISSUE TITLE
cannot work with the inD dataser

### ISSUE THREAD

**Issue by qxqiang** [Kguo-cs/TDOR#3]
Dear authors:
Thank you very much for your work.  I've been learning about your article recently, and I've encountered some problems. I hope to get your kind help.
 I have downloaded the inD dataset,  and got the "inD_train.pickle" and "inD_test.pickle" .   But the code doesn't work properly.  The main error is: 
"  File "F:\trajectorypredicion\data\IND\inD.py", line 12, in __init__
    D = np.load("./data/IND/"+dataset+"_"+type + ".npy")
   FileNotFoundError: [Errno 2] No such file or directory: './data/IND/ind_train.npy'
"
It seems that the " ind_train.npy" and "ind_test.npy files are missing.

Then I got the "ind_train.npy" and "ind_test.npy"  dataset by modifying the "preprocessing_inD.py" code. but the "train.py" still doesn't work properly.  The  main error is 

" File "F:\trajectorypredicion\data\IND\inD.py", line 27, in __init__
    i_list = np.unique(D[:, 0, -1])
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed"

I don't know if there are any other bugs

This problem has been bothering me for a long time. I don't know if there are any other bugs. could you please help me?

Sorry for my stupid questions, after a careful check, it works.

**Comment by Kguo-cs** [comment]
We got the "inD_train.pickle" and "inD_test.pickle" from Y-net, which are deleted now due to copyright. I may send the  "ind_train.npy" and "ind_test.npy"  to your email.

**Comment by qxqiang** [comment]
> We got the "inD_train.pickle" and "inD_test.pickle" from Y-net, which are deleted now due to copyright. I may send the "ind_train.npy" and "ind_test.npy" to your email.

Thank you very much for your reply. I have obtained the dataset from the official website,  my computer is configured with an Intel Core i7-8750H CPU 2.20GHz and 16GB RAM.   Could you please tell me the computer configuration and the training time？ I tried to train the network with all the inD datasets and found that it took a lot of time.  So, I tried to train with a small amount of data and found that I couldn't get the ”model_state_dict“ file.  I guess it may be caused by insufficient training data?


Epoch no: 0 | temp 1.00000 | val 192.806 | ade 0.000 | policy 0.000 | traj 0.000 |ce 0.000 | ogms_rce 0.000 | ogms_ce 192.806 | Min epoch 0 | Min val loss 192.806 | T(s): 13
...
Epoch no: 99 | temp 0.80570 | val 282.397 | ade 0.000 | policy 18.629 | traj 239.623 |ce 258.252 | ogms_rce 120.724 | ogms_ce 0.000 | Min epoch 64 | Min val loss 80.790 | T(s): 10
Epoch no: 100 | temp 0.93987 | val 60.455 | ade 60.455 | policy 0.000 | traj 0.000 |ce 0.000 | ogms_rce 0.000 | ogms_ce 0.000 | Min epoch 100 | Min val loss 60.455 | T(s): 10
...
Epoch no: 799 | temp 0.93987 | val 20.061 | ade 20.061 | policy 0.000 | traj 0.000 |ce 0.000 | ogms_rce 0.000 | ogms_ce 0.000 | Min epoch 256 | Min val loss 15.522 | T(s): 11

**Comment by Kguo-cs** [comment]
I'm not sure whether the dataset from the official website is the same as the dataset provided by Y-net. The dataset provided by Y-net can finished within a day with one Geforce-3090.

**Comment by qxqiang** [comment]
> I'm not sure whether the dataset from the official website is the same as the dataset provided by Y-net. The dataset provided by Y-net can finished within a day with one Geforce-3090.

thank you for your reply.  I probably calculated that it will take half a month for training on my computer. Maybe the data is different, and I don't know.  Could you please send the "inD_test.pickle" , "inD_train.pickle", "ind_train.npy" and "ind_test.npy" to my email<178869742@qq.com>?

**Comment by chuinixiongkou** [comment]
I am also facing the same problem, could you please provide the "inD_test.pickle" , "inD_train.pickle", "ind_train.npy" and "ind_test.npy" to my email lizz8782@163.com?

**Comment by Kguo-cs** [comment]
I have sent it. I trained for a day.

**Comment by chuinixiongkou** [comment]
Thank you so much!




李志泽
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kguo-cs/TDOR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kguo-cs/TDOR] cannot work with the inD dataser (Issue #3)





 
I have sent it. I trained for a day.

**Comment by qxqiang** [comment]
我都忘了他给没给，晚上回去找一波



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 22, 2023 11:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Kguo-cs/TDOR] cannot work with the inD dataser (Issue #3)




 
I am also facing the same problem, could you please provide the "inD_test.pickle" , "inD_train.pickle", "ind_train.npy" and "ind_test.npy" to my email ***@***.***?
