### ISSUE TITLE
question about the neighbors number

### ISSUE THREAD

**Issue by qxqiang** [Kguo-cs/TDOR#4]
Hello, I have a question about neighbors in the inD dataset, when using the inD dataset, the neighbors’ number is set to 0, does it not consider the relationship between other pedestrians and the target agent? However, neighbors are considered in the SDD dataset, it seems the neighbors_num =2. Is it possible to consider only 2 pedestrians around at most?

**Comment by Kguo-cs** [comment]
The neighbor number can be adjusted based on the human density in the dataset. The human considered in the inD have very small neighbor number. For simplity, it can be set to 0.
